### ISSUE TITLE
Markdown on PyPI

### ISSUE THREAD

**Issue by MartinThoma** [Teemu/pytest-sugar#207]
When I go to the [pytest-sugar page on PyPI](https://pypi.org/project/pytest-sugar), I see that markdown is not rendered. The version there is 0.9.4 and if [there](https://github.com/Teemu/pytest-sugar/blob/master/pytest_sugar.py#L31) were no other changes, this version was introduced with 92ae9dee - the latest commit.

I'm uncertain why markdown is not rendered, though. I have a similar setup for my packages and they look fine. Does anybody here have an idea?

**Comment by Teemu** [comment]
Interesting, I don't know what's going on with that. I read the documentations and I have the markdown tag correctly there.

**Comment by MartinThoma** [comment]
@Teemu Could you please answer the questions in the other issue? pypa/warehouse is the official repository of pypi.org; so the folks there should be able to give awesome support :-)

**Comment by mgedmin** [comment]
From my previous encounters with this kind of problem, you need a few things in order to use Markdown descriptions on PyPI:

- a `long_description_content_type="text/markdown"` in your setup.py (which you have)
- a sufficiently recent setuptools version used to build the sdist (can't find an exact version number, sorry!)
- a sufficiently recent twine version (>= 1.11) used to upload the sdist to PyPI

If you're uploading wheels, it might also be a good idea that you have the most recent [wheel](https://pypi.org/project/wheel/) version as well.

Anyway I've looked at the two PKG-INFO files inside pytest-sugar-0.9.4.tar.gz and neither of them has the 

    Description-Content-Type: text/markdown

field, which indicates that you used a too-old setuptools version to generate the sdist.

**Comment by MartinThoma** [comment]
@Teemu Could you answer the questions in https://github.com/pypa/warehouse/issues/8472 about the pytest-sugar build? Maybe they can help us to fix it.

**Comment by pradyunsg** [comment]
> field, which indicates that you used a too-old setuptools version to generate the sdist.

I'm 100% sure that this was the case. :)

I suggest running `twine check` on the distributions before uploading them (which prints the warning appropriately).

**Comment by blueyed** [comment]
Closing as per previous comment.
